### ISSUE TITLE
Unable to install via brew or docker

### ISSUE THREAD

**Issue by ebarrere** [robusta-dev/holmesgpt#121]
I would like to try this tool but I [can't install via brew](https://github.com/robusta-dev/homebrew-holmesgpt/issues/1) or podman.

```
$ podman pull --tls-verify=false us-central1-docker.pkg.dev/genuine-flight-317411/devel/holmes-dev
Trying to pull us-central1-docker.pkg.dev/genuine-flight-317411/devel/holmes-dev:latest...
Error: initializing source docker://us-central1-docker.pkg.dev/genuine-flight-317411/devel/holmes-dev:latest: reading manifest latest in us-central1-docker.pkg.dev/genuine-flight-317411/devel/holmes-dev: manifest unknown: Failed to fetch "latest"
$
```

**Comment by aantn** [comment]
Hi, thanks for reporting. It is a mistake in the readme. Can you please try with the image `us-central1-docker.pkg.dev/genuine-flight-317411/devel/holmes` (no `-dev` at the end)

**Comment by ebarrere** [comment]
Thanks, that fixed it!On Sep 2, 2024, at 10:44 AM, Natan Yellin ***@***.***> wrote:﻿
Hi, thanks for reporting. It is a mistake in the readme. Can you please try with the image us-central1-docker.pkg.dev/genuine-flight-317411/devel/holmes (no -dev at the end)

**Comment by aantn** [comment]
Awesome, happy to hear it!
