### ISSUE TITLE
New Feature: GitHub Issues

### ISSUE THREAD

**Issue by Vahan90** [robusta-dev/holmesgpt#13]
## Objective

- Just inquiring whether it's a needed / useful feature to have `holmesgpt` work with GitHub issues, in a similar fashion as it works with `Jira` tickets?
- If it's useful, I don't mind contributing and doing a PR to add that feature here.

**Comment by aantn** [comment]
Yes! It would be a great feature. Please contribute the PR and I will be happy to help if useful.

**Comment by Vahan90** [comment]
#28 is here and ready for a review

**Comment by aantn** [comment]
Merged :)
