### ISSUE TITLE
[Feature request] - Operator inside Kubernetes.

### ISSUE THREAD

**Issue by larssb** [robusta-dev/holmesgpt#15]
This would be awesome. Having holmesgpt running inside Kubernetes to report on and eventually self-heal ( to the extend possible ), any issues seen.

Would this be possible. And what about doing something together with https://k8sgpt.ai/? I see some overlap in general between K8sGPT and HolmesGPT.

Thanks

**Comment by arikalon1** [comment]
Hey @larssb 

We're about to release `holmes` running in the cluster really soon, which will be able to automatically investigate and report issues.

**Comment by pavangudiwada** [comment]
@larssb, running ``holmes`` in cluster is now possible with Robusta. Please take a look here: https://github.com/robusta-dev/robusta/releases/tag/0.14.0
