### ISSUE TITLE
Using brew to install shows error

### ISSUE THREAD

**Issue by cooper-car** [robusta-dev/holmesgpt#219]
follow the two commands on github：
`brew tap robusta-dev/homebrew-holmesgpt`
`brew install holmesgpt`

shows error below：
![CleanShot 2024-12-06 at 11 18 57@2x](https://github.com/user-attachments/assets/7d1612cf-0991-468c-ada6-f0849d320cc3)

**Comment by arikalon1** [comment]
Hi @cooper-car 

Thanks for reporting this.
The 0.7.0 release wasn't uploaded properly
I created a new release, 0.7.1 which should work fine.

Please try installing again
`brew tap robusta-dev/homebrew-holmesgpt`
`brew install holmesgpt`

**Comment by cooper-car** [comment]
Hi, @arikalon1 

Thank you for the fix!  👍
